version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
