services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: host
    environment:
      - FLASK_APP=app/flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PORT=3050
      - MAWAQIT_USERNAME=MAWAQIT_USERNAME
      - MAWAQIT_PASSWORD=MAWAQIT_PASSWORD
      - MAWAQIT_MOSQUE=MAWAQIT_MOSQUE
      - DEVICE_NAME=DEVICE_NAME
      - CHROMECAST_IP=CHROMECAST_IP
