version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.9
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - run:
          name: Install Pre-requisites
          command: ./.circleci/scripts/install-changelog-manager.sh
      - run:
          name: Get Version
          command: TAG_VERSION="$(changelog-manager suggest)"
      - docker/check
      - docker/build:
          image: ahmadmasri/athan
          tag: ${TAG_VERSION}
          dockerfile: Dockerfile
      - docker/push:
          image: ahmadmasri/athan
          tag: ${TAG_VERSION}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
