version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - docker/check:
          registry-url: https://index.docker.io/v1/
      - docker/build:
          image: your_dockerhub_username/your_image_name
          tag: your_image_tag
          dockerfile: Dockerfile
          deployment: true
          registry: https://index.docker.io/v1/
          requires:
            - setup_remote_docker
      - docker/push:
          image: your_dockerhub_username/your_image_name
          tag: your_image_tag
          registry: https://index.docker.io/v1/

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
